# Generated by Django 2.1.5 on 2019-02-12 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='group',
            field=models.ForeignKey(null='true', on_delete=django.db.models.deletion.CASCADE, to='phone.Grp'),
        ),
    ]
