# Generated by Django 2.1.5 on 2019-02-19 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0002_auto_20190213_0007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='number',
            field=models.IntegerField(verbose_name=12),
        ),
    ]
